### ISSUE TITLE
Active/functional project?

### ISSUE THREAD

**Issue by laryn** [Webskillet/webform_salsa#1]
Hello! I'm curious if this is an active/functional project, or if it is in use on a live site? I don't see any releases so just wanted to check in on the status.

Thanks.

**Comment by jkissam** [comment]
Hi Laryn,

I don't _think_ this is in use anywhere, as most of my clients stopped using Salsa 3-4 years ago, but it is possible that I am forgetting someone. If Salsa's API still allows posting to the /save endpoint without authentication, then it should still work. I'm about to leave more extensive commentary on the [webform_external](https://github.com/Webskillet/webform_external/issues/1) module, though...

Jonathan

**Comment by laryn** [comment]
Thanks Jonathan!

**Comment by ahillio** [comment]
This module is still in use on http://vermontearlychildhoodalliance.org/.
